(define (max X)
	(if (null? (cdr X)) 
		(car X) 
		(if (< (car X) (max (cdr X)))  
    	(max (cdr X)) 
	   	(car X)
		)
	)
)

(define (min Y)
	(if (null? (cdr Y)) 
		(car Y) 
		(if (> (car Y) (min (cdr Y)))  
		(min (cdr Y)) 
		(car Y)
		)
	)
)

(define lista (list 33 41 1 -3 15 0 924 -374 -10))

(display (max lista))
(newline)
(display (min lista))
